# Generated by Django 3.2.15 on 2022-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[], default='Uncategorized', max_length=255),
        ),
    ]
