# Generated by Django 3.2.15 on 2022-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Album', 'Album'), ('Concert', 'Concert'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[(0, 'Electronic'), (2, 'Folk/Country'), (3, 'Jazz'), (4, 'Pop/R&B'), (5, 'Rock'), (6, 'Experimental'), (7, 'Global'), (8, 'Metal'), (9, 'Rap/Hip-Hop')], max_length=255),
        ),
    ]
