# Generated by Django 3.2.15 on 2022-09-28 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220926_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='release_live_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
