# Generated by Django 3.2.15 on 2022-09-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_post_release_live_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='release_date',
        ),
    ]
