# Generated by Django 3.2.15 on 2022-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20221003_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Album', 'Album'), ('Concert', 'Concert'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Experimental', 'Experimental'), ('Folk/Country', 'Folk/Country'), ('Global', 'Global'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Pop/R&B', 'Pop/R&B'), ('Rap/Hip-Hop', 'Rap/Hip-Hop'), ('Rock', 'Rock'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
