# Generated by Django 3.2.15 on 2022-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20221003_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fragment',
            field=models.TextField(),
        ),
    ]
