# Generated by Django 3.2.15 on 2022-10-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20221009_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='presentation',
            field=models.TextField(max_length=500),
        ),
    ]
